# coding: utf-8

"""
    Irisnet API

    Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.

    The version of the OpenAPI document: v2
    Contact: info@irisnet.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import irisnet_client
from irisnet_client.api.balance_endpoints_api import BalanceEndpointsApi  # noqa: E501
from irisnet_client.rest import ApiException


class TestBalanceEndpointsApi(unittest.TestCase):
    """BalanceEndpointsApi unit test stubs"""

    def setUp(self):
        self.api = irisnet_client.api.balance_endpoints_api.BalanceEndpointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cost(self):
        """Test case for get_cost

        Get the cost of the configuration for a single image.  # noqa: E501
        """
        pass

    def test_get_license_info(self):
        """Test case for get_license_info

        Get information for the given license key.  # noqa: E501
        """
        pass

    def test_get_video_cost(self):
        """Test case for get_video_cost

        Get the cost of the configuration for moving images.  # noqa: E501
        """
        pass

    def test_get_video_cost1(self):
        """Test case for get_video_cost1

        Get the cost of the configuration for moving images.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
