# coding: utf-8

"""
    Irisnet API

    Artificial Intelligence (AI) for image- and video-processing in realtime. This is an interactive documentation meant to give a place were you can quickly look up the endpoints and their schemas, while also giving you the option to try things out yourself.  Listed below you'll see the available endpoints of the API that can be expanded by clicking on it. Each expanded endpoint lists the request parameter (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail. Additionally you'll find a 'Try it out' button where you can type in your custom parameters and custom body and execute that against the API. The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses.By clicking on the right arrow you can expand the model and it will show you a description of the model and the model parameters. For nested models you can keep clicking the right arrow to reveal further details on it.    # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import irisnet_client
from irisnet_client.api.endpoints_to_setup_the_ai_api import EndpointsToSetupTheAIApi  # noqa: E501
from irisnet_client.rest import ApiException


class TestEndpointsToSetupTheAIApi(unittest.TestCase):
    """EndpointsToSetupTheAIApi unit test stubs"""

    def setUp(self):
        self.api = irisnet_client.api.endpoints_to_setup_the_ai_api.EndpointsToSetupTheAIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_set_in_define(self):
        """Test case for set_in_define

        Set definitions via pre-defined prototypes.  # noqa: E501
        """
        pass

    def test_set_in_params(self):
        """Test case for set_in_params

        Set the behaviour parameters for one object class.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
