# coding: utf-8

"""
    Irisnet API

    Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.

    The version of the OpenAPI document: v2
    Contact: info@irisnet.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from irisnet_client.models.poa_document_detection import PoaDocumentDetection

class TestPoaDocumentDetection(unittest.TestCase):
    """PoaDocumentDetection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PoaDocumentDetection:
        """Test PoaDocumentDetection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PoaDocumentDetection`
        """
        model = PoaDocumentDetection()
        if include_optional:
            return PoaDocumentDetection(
                classification = 'face',
                group = 'human',
                id = 1003,
                probability = 94,
                coordinates = irisnet_client.models.coordinates.Coordinates(
                    rectangles = [
                        irisnet_client.models.rectangle.Rectangle(
                            x0 = 0.1, 
                            y0 = 0.1, 
                            width = 0.1, 
                            height = 0.1, )
                        ], 
                    segments = [
                        irisnet_client.models.segment.Segment(
                            start = 0, 
                            end = 3, )
                        ], ),
                check_id = '',
                processed_checks = irisnet_client.models.poa_document_sub_checks.PoaDocumentSubChecks(
                    first_name = 'passed', 
                    last_name = 'passed', 
                    document_age = 'passed', 
                    ip_originates_in_address_country = 'passed', 
                    ip_nearby_address = 'passed', ),
                attributes = [
                    irisnet_client.models.poa_document_attribute.PoaDocumentAttribute(
                        type = 'BaseAttribute', 
                        name = '', 
                        document_type = 'national_identity_card', 
                        issuer = '', 
                        issuing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        address = '', 
                        address_country = 'DE', )
                    ],
                document_holder_id = ''
            )
        else:
            return PoaDocumentDetection(
        )
        """

    def testPoaDocumentDetection(self):
        """Test PoaDocumentDetection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
