"""
    Irisnet API

    Artificial Intelligence (AI) for image- and video-processing in realtime. This is an interactive documentation meant to give a place were you can quickly look up the endpoints and their schemas, while also giving you the option to try things out yourself.  Listed below you'll see the available endpoints of the API that can be expanded by clicking on it. Each expanded endpoint lists the request parameter (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail. Additionally you'll find a 'Try it out' button where you can type in your custom parameters and custom body and execute that against the API. The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. By clicking on the right arrow you can expand the model and it will show you a description of the model and the model parameters. For nested models you can keep clicking the right arrow to reveal further details on it.    # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from irisnet_client.api_client import ApiClient, Endpoint as _Endpoint
from irisnet_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from irisnet_client.model.in_error import INError
from irisnet_client.model.iris_net import IrisNet


class EndpointsForAIChecksApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.check_image_endpoint = _Endpoint(
            settings={
                'response_type': (IrisNet,),
                'auth': [],
                'endpoint_path': '/v1/check-image/{licenseKey}',
                'operation_id': 'check_image',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'license_key',
                    'file',
                    'detail',
                    'image_encode',
                ],
                'required': [
                    'license_key',
                    'file',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'license_key':
                        (str,),
                    'file':
                        (file_type,),
                    'detail':
                        (int,),
                    'image_encode':
                        (bool,),
                },
                'attribute_map': {
                    'license_key': 'licenseKey',
                    'file': 'file',
                    'detail': 'detail',
                    'image_encode': 'imageEncode',
                },
                'location_map': {
                    'license_key': 'path',
                    'file': 'form',
                    'detail': 'query',
                    'image_encode': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/xml',
                    'application/json'
                ],
                'content_type': [
                    'multipart/form-data'
                ]
            },
            api_client=api_client
        )
        self.check_image_url_endpoint = _Endpoint(
            settings={
                'response_type': (IrisNet,),
                'auth': [],
                'endpoint_path': '/v1/check-url/{licenseKey}',
                'operation_id': 'check_image_url',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'url',
                    'license_key',
                    'detail',
                    'image_encode',
                ],
                'required': [
                    'url',
                    'license_key',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'url':
                        (str,),
                    'license_key':
                        (str,),
                    'detail':
                        (int,),
                    'image_encode':
                        (bool,),
                },
                'attribute_map': {
                    'url': 'url',
                    'license_key': 'licenseKey',
                    'detail': 'detail',
                    'image_encode': 'imageEncode',
                },
                'location_map': {
                    'url': 'query',
                    'license_key': 'path',
                    'detail': 'query',
                    'image_encode': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/xml',
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )

    def check_image(
        self,
        license_key,
        file,
        **kwargs
    ):
        """Upload and check image against previously chosen configuration.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.check_image(license_key, file, async_req=True)
        >>> result = thread.get()

        Args:
            license_key (str): License obtained from irisnet.de shop.
            file (file_type):

        Keyword Args:
            detail (int): Sets the response details.  * _1_ - The response body informs you if the image is ok or not ok (better API performance) * _2_ - In addition the response body lists all broken rules. * _3_ - In addition to the first two options, this will show all objects with positional information.. [optional] if omitted the server will use the default value of 1
            image_encode (bool): Specifies whether or not to draw an output image that can be downloaded afterwards.. [optional] if omitted the server will use the default value of False
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            IrisNet
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['license_key'] = \
            license_key
        kwargs['file'] = \
            file
        return self.check_image_endpoint.call_with_http_info(**kwargs)

    def check_image_url(
        self,
        url,
        license_key,
        **kwargs
    ):
        """Check image url against previously chosen configuration.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.check_image_url(url, license_key, async_req=True)
        >>> result = thread.get()

        Args:
            url (str):
            license_key (str): License obtained from irisnet.de shop.

        Keyword Args:
            detail (int): Sets the response details.  * _1_ - The response body informs you if the image is ok or not ok (better API performance) * _2_ - In addition the response body lists all broken rules. * _3_ - In addition to the first two options, this will show all objects with positional information.. [optional] if omitted the server will use the default value of 1
            image_encode (bool): Specifies whether or not to draw an output image that can be downloaded afterwards.. [optional] if omitted the server will use the default value of False
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            IrisNet
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['url'] = \
            url
        kwargs['license_key'] = \
            license_key
        return self.check_image_url_endpoint.call_with_http_info(**kwargs)

