# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import irisnet_client
from irisnet_client.paths.v2_cost_config_id_frames import get  # noqa: E501
from irisnet_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV2CostConfigIdFrames(ApiTestMixin, unittest.TestCase):
    """
    V2CostConfigIdFrames unit test stubs
        Get the cost of the configuration for moving images.  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 429




if __name__ == '__main__':
    unittest.main()
