# coding: utf-8

"""
    Irisnet API

    Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.

    The version of the OpenAPI document: v2
    Contact: info@irisnet.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist

class Summary(BaseModel):
    """
    Summarizing the result of the AI.  # noqa: E501
    """
    status: Optional[StrictStr] = Field(None, description="A simple status string that can be either _accept_ or _reject_.")
    broken_rules_count: Optional[StrictInt] = Field(None, alias="brokenRulesCount", description="The amount of broken rules that are contained in the source media.")
    help_suggested: Optional[StrictInt] = Field(None, alias="helpSuggested", description="In cases where the AI is uncertain, this attribute is set (1), indication that it could be useful to double check the source media by a human.")
    severity: Optional[StrictInt] = Field(None, description="The highest severity value found amongst the broken rules.")
    credits_consumed: Optional[StrictInt] = Field(None, alias="creditsConsumed", description="The amount of credits that was consumed for the check.")
    tags: Optional[conlist(StrictStr, unique_items=True)] = Field(None, description="A list of classification names that were found.")
    reject_tags: Optional[conlist(StrictStr, unique_items=True)] = Field(None, alias="rejectTags", description="A list of classification names that caused a rule to be broken.")
    reject_reasons: Optional[conlist(StrictStr, unique_items=True)] = Field(None, alias="rejectReasons", description="The names of the classification groups that caused a rule to be broken.")
    __properties = ["status", "brokenRulesCount", "helpSuggested", "severity", "creditsConsumed", "tags", "rejectTags", "rejectReasons"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Summary:
        """Create an instance of Summary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Summary:
        """Create an instance of Summary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Summary.parse_obj(obj)

        _obj = Summary.parse_obj({
            "status": obj.get("status"),
            "broken_rules_count": obj.get("brokenRulesCount"),
            "help_suggested": obj.get("helpSuggested"),
            "severity": obj.get("severity"),
            "credits_consumed": obj.get("creditsConsumed"),
            "tags": obj.get("tags"),
            "reject_tags": obj.get("rejectTags"),
            "reject_reasons": obj.get("rejectReasons")
        })
        return _obj


