# coding: utf-8

"""
    Irisnet API

    Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.

    The version of the OpenAPI document: v2
    Contact: info@irisnet.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Summary(BaseModel):
    """
    Summarizing the result of the AI.
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="A simple status string that can be either _accept_ or _reject_.")
    broken_rules_count: Optional[StrictInt] = Field(default=None, description="The amount of broken rules that are contained in the source media.", alias="brokenRulesCount")
    help_suggested: Optional[StrictInt] = Field(default=None, description="In cases where the AI is uncertain, this attribute is set (1), indication that it could be useful to double check the source media by a human.", alias="helpSuggested")
    severity: Optional[StrictInt] = Field(default=None, description="The highest severity value found amongst the broken rules.")
    credits_consumed: Optional[StrictInt] = Field(default=None, description="The amount of credits that was consumed for the check.", alias="creditsConsumed")
    tags: Optional[List[StrictStr]] = Field(default=None, description="A list of classification names that were found.")
    reject_tags: Optional[List[StrictStr]] = Field(default=None, description="A list of classification names that caused a rule to be broken.", alias="rejectTags")
    reject_reasons: Optional[List[StrictStr]] = Field(default=None, description="The names of the classification groups that caused a rule to be broken.", alias="rejectReasons")
    __properties: ClassVar[List[str]] = ["status", "brokenRulesCount", "helpSuggested", "severity", "creditsConsumed", "tags", "rejectTags", "rejectReasons"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Summary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Summary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "brokenRulesCount": obj.get("brokenRulesCount"),
            "helpSuggested": obj.get("helpSuggested"),
            "severity": obj.get("severity"),
            "creditsConsumed": obj.get("creditsConsumed"),
            "tags": obj.get("tags"),
            "rejectTags": obj.get("rejectTags"),
            "rejectReasons": obj.get("rejectReasons")
        })
        return _obj


